"""
Test Suite for Recurring Task Deletion Fix
Tests that deleted recurring tasks don't reappear in autogenerated schedules
"""

import pytest
import json
from unittest.mock import Mock, patch, MagicMock
from datetime import datetime, timedelta
from bson import ObjectId

from backend.apis.routes import api_bp
from backend.services.schedule_service import ScheduleService


class TestRecurringTaskDeletion:
    """Test cases for recurring task deletion functionality"""

    @pytest.fixture
    def mock_app(self):
        """Create a test Flask app with the API blueprint"""
        from flask import Flask
        app = Flask(__name__)
        app.register_blueprint(api_bp, url_prefix='/api')
        app.config['TESTING'] = True
        return app

    @pytest.fixture
    def mock_user_schedules_collection(self):
        """Mock user schedules collection"""
        mock_collection = Mock()
        return mock_collection

    @pytest.fixture
    def sample_schedule_with_recurring_task(self):
        """Sample schedule with a daily recurring task"""
        return {
            "_id": ObjectId("507f1f77bcf86cd799439011"),
            "userId": "test_user_123",
            "date": "2025-01-20T00:00:00",
            "schedule": [
                {
                    "id": "recurring-task-1",
                    "text": "Daily Exercise",
                    "categories": ["Health"],
                    "completed": False,
                    "is_section": False,
                    "type": "task",
                    "is_recurring": {
                        "frequency": "daily",
                        "status": "active"
                    }
                },
                {
                    "id": "regular-task-1",
                    "text": "Regular task",
                    "categories": ["Work"],
                    "completed": False,
                    "is_section": False,
                    "type": "task"
                }
            ],
            "metadata": {
                "created_at": "2025-01-20T08:00:00",
                "last_modified": "2025-01-20T08:00:00",
                "source": "manual"
            }
        }

    @pytest.fixture
    def sample_schedule_with_stopped_recurring_task(self):
        """Sample schedule with a stopped recurring task"""
        return {
            "_id": ObjectId("507f1f77bcf86cd799439012"),
            "userId": "test_user_123",
            "date": "2025-01-21T00:00:00",
            "schedule": [
                {
                    "id": "recurring-task-1-stopped",
                    "text": "Daily Exercise",
                    "categories": ["Health"],
                    "completed": False,
                    "is_section": False,
                    "type": "task",
                    "is_recurring": {
                        "frequency": "daily",
                        "status": "stopped"
                    }
                }
            ],
            "metadata": {
                "created_at": "2025-01-21T08:00:00",
                "last_modified": "2025-01-21T09:00:00",
                "source": "manual"
            }
        }

    def test_delete_recurring_task_sets_status_to_stopped(self, mock_app, sample_schedule_with_recurring_task):
        """Test that deleting a recurring task removes it from schedule and adds to exclusion list"""

        with patch('backend.apis.routes.get_user_from_token') as mock_get_user, \
             patch('backend.apis.routes.schedule_service') as mock_schedule_service, \
             patch('backend.apis.routes.get_users_collection') as mock_get_users_collection:

            # Setup mocks
            mock_get_user.return_value = {'googleId': 'test_user_123'}
            mock_schedule_service.get_schedule_by_date.return_value = (
                True,
                {"schedule": sample_schedule_with_recurring_task["schedule"], "date": "2025-01-20"}
            )

            # Expected schedule after deletion - recurring task should be REMOVED
            expected_schedule_after_delete = [
                {
                    "id": "regular-task-1",
                    "text": "Regular task",
                    "categories": ["Work"],
                    "completed": False,
                    "is_section": False,
                    "type": "task"
                }
            ]

            mock_schedule_service.update_schedule_tasks.return_value = (
                True,
                {
                    "schedule": expected_schedule_after_delete,
                    "date": "2025-01-20",
                    "metadata": {"totalTasks": 1}
                }
            )

            # Mock users collection
            mock_users_coll = Mock()
            mock_get_users_collection.return_value = mock_users_coll

            # Test the API endpoint
            with mock_app.test_client() as client:
                response = client.delete(
                    '/api/tasks/recurring-task-1',
                    headers={
                        'Authorization': 'Bearer valid_token',
                        'Content-Type': 'application/json'
                    },
                    json={'date': '2025-01-20'}
                )

                # Verify response
                assert response.status_code == 200
                response_data = json.loads(response.data)
                assert response_data['success'] is True

                # Verify that update_schedule_tasks was called with the recurring task removed
                mock_schedule_service.update_schedule_tasks.assert_called_once()
                call_args = mock_schedule_service.update_schedule_tasks.call_args
                updated_schedule = call_args[0][2]  # Third argument is the updated schedule

                # Verify the recurring task was removed from schedule
                recurring_task = next(
                    (task for task in updated_schedule if task['id'] == 'recurring-task-1'),
                    None
                )
                assert recurring_task is None, "Recurring task should be removed from schedule"

                # Verify that exclusion was added to user document
                mock_users_coll.update_one.assert_called_once()

    def test_autogenerate_skips_stopped_recurring_tasks(self, mock_user_schedules_collection):
        """Test that autogenerate_schedule skips recurring tasks with status = 'stopped'"""

        # Mock schedule service and collection
        schedule_service = ScheduleService()
        schedule_service.schedules_collection = mock_user_schedules_collection

        # Mock data: previous day has a stopped recurring task
        previous_schedule = {
            "userId": "test_user_123",
            "date": "2025-01-20T00:00:00",
            "schedule": [
                {
                    "id": "recurring-task-1",
                    "text": "Daily Exercise",
                    "categories": ["Health"],
                    "completed": False,
                    "is_section": False,
                    "type": "task",
                    "is_recurring": {
                        "frequency": "daily",
                        "status": "stopped"  # This should NOT be included in next day
                    }
                }
            ]
        }

        # Mock database queries
        # find_one is called for: 1) check existing schedule, 2) check recent inputs
        mock_user_schedules_collection.find_one.side_effect = [
            None,  # No existing schedule for target date
            None,  # No recent schedule with inputs
        ]

        # Mock find() for range queries (used by _find_most_recent_schedule_matching)
        # Create a mock cursor that returns the previous schedule
        mock_cursor = MagicMock()
        mock_cursor.__iter__.return_value = iter([previous_schedule])
        mock_cursor.sort.return_value = mock_cursor
        mock_user_schedules_collection.find.return_value = mock_cursor

        mock_user_schedules_collection.database = {'users': Mock()}
        mock_user_schedules_collection.database['users'].find_one.return_value = None

        mock_user_schedules_collection.replace_one.return_value = Mock(upserted_id=None)

        # Test autogenerate
        with patch('backend.services.calendar_service.get_calendar_tasks_for_user_date') as mock_calendar:
            mock_calendar.return_value = []  # No calendar tasks

            success, result = schedule_service.autogenerate_schedule(
                user_id="test_user_123",
                date="2025-01-21"
            )

            # Verify success
            assert success is True
            assert result['created'] is True

            # Verify that the stopped recurring task was NOT included in the new schedule
            generated_schedule = result['schedule']
            recurring_tasks = [
                task for task in generated_schedule
                if task.get('text') == 'Daily Exercise'
            ]
            assert len(recurring_tasks) == 0, "Stopped recurring task should not appear in autogenerated schedule"

    def test_autogenerate_includes_active_recurring_tasks(self, mock_user_schedules_collection):
        """Test that autogenerate_schedule includes recurring tasks with status = 'active'"""

        # Mock schedule service and collection
        schedule_service = ScheduleService()
        schedule_service.schedules_collection = mock_user_schedules_collection

        # Mock data: previous day has an active recurring task
        previous_schedule = {
            "userId": "test_user_123",
            "date": "2025-01-20T00:00:00",
            "schedule": [
                {
                    "id": "recurring-task-1",
                    "text": "Daily Exercise",
                    "categories": ["Health"],
                    "completed": False,
                    "is_section": False,
                    "type": "task",
                    "is_recurring": {
                        "frequency": "daily",
                        "status": "active"  # This should be included in next day
                    }
                }
            ]
        }

        # Mock database queries
        # find_one is called for: 1) check existing schedule, 2) check recent inputs
        mock_user_schedules_collection.find_one.side_effect = [
            None,  # No existing schedule for target date
            None,  # No recent schedule with inputs
        ]

        # Mock find() for range queries (used by _find_most_recent_schedule_matching)
        # Create a mock cursor that returns the previous schedule
        mock_cursor = MagicMock()
        mock_cursor.__iter__.return_value = iter([previous_schedule])
        mock_cursor.sort.return_value = mock_cursor
        mock_user_schedules_collection.find.return_value = mock_cursor

        mock_user_schedules_collection.database = {'users': Mock()}
        mock_user_schedules_collection.database['users'].find_one.return_value = None

        mock_user_schedules_collection.replace_one.return_value = Mock(upserted_id=None)

        # Test autogenerate
        with patch('backend.services.calendar_service.get_calendar_tasks_for_user_date') as mock_calendar:
            mock_calendar.return_value = []  # No calendar tasks

            success, result = schedule_service.autogenerate_schedule(
                user_id="test_user_123",
                date="2025-01-21"
            )

            # Verify success
            assert success is True
            assert result['created'] is True

            # Verify that the active recurring task WAS included in the new schedule
            generated_schedule = result['schedule']
            recurring_tasks = [
                task for task in generated_schedule
                if task.get('text') == 'Daily Exercise' and task.get('is_recurring')
            ]
            assert len(recurring_tasks) == 1, "Active recurring task should appear in autogenerated schedule"
            assert recurring_tasks[0]['is_recurring']['status'] == 'active'

    def test_recurring_task_without_status_defaults_to_active(self, mock_user_schedules_collection):
        """Test backward compatibility: recurring tasks without status field default to active"""

        # Mock schedule service and collection
        schedule_service = ScheduleService()
        schedule_service.schedules_collection = mock_user_schedules_collection

        # Mock data: previous day has a recurring task WITHOUT status field (backward compatibility)
        previous_schedule = {
            "userId": "test_user_123",
            "date": "2025-01-20T00:00:00",
            "schedule": [
                {
                    "id": "recurring-task-1",
                    "text": "Daily Exercise",
                    "categories": ["Health"],
                    "completed": False,
                    "is_section": False,
                    "type": "task",
                    "is_recurring": {
                        "frequency": "daily"
                        # No status field - should default to active
                    }
                }
            ]
        }

        # Mock database queries
        # find_one is called for: 1) check existing schedule, 2) check recent inputs
        mock_user_schedules_collection.find_one.side_effect = [
            None,  # No existing schedule for target date
            None,  # No recent schedule with inputs
        ]

        # Mock find() for range queries (used by _find_most_recent_schedule_matching)
        # Create a mock cursor that returns the previous schedule
        mock_cursor = MagicMock()
        mock_cursor.__iter__.return_value = iter([previous_schedule])
        mock_cursor.sort.return_value = mock_cursor
        mock_user_schedules_collection.find.return_value = mock_cursor

        mock_user_schedules_collection.database = {'users': Mock()}
        mock_user_schedules_collection.database['users'].find_one.return_value = None

        mock_user_schedules_collection.replace_one.return_value = Mock(upserted_id=None)

        # Test autogenerate
        with patch('backend.services.calendar_service.get_calendar_tasks_for_user_date') as mock_calendar:
            mock_calendar.return_value = []  # No calendar tasks

            success, result = schedule_service.autogenerate_schedule(
                user_id="test_user_123",
                date="2025-01-21"
            )

            # Verify success
            assert success is True
            assert result['created'] is True

            # Verify that the recurring task without status WAS included (defaults to active)
            generated_schedule = result['schedule']
            recurring_tasks = [
                task for task in generated_schedule
                if task.get('text') == 'Daily Exercise' and task.get('is_recurring')
            ]
            assert len(recurring_tasks) == 1, "Recurring task without status should default to active and appear in schedule"