"""
Test Suite for Recurring Task Deletion with Exclusion Pattern
Tests that deleted recurring tasks are added to user's exclusion list
and don't reappear in autogenerated schedules.
"""

import pytest
import json
from unittest.mock import Mock, patch, MagicMock
from datetime import datetime, timezone, timedelta
from bson import ObjectId

from backend.apis.routes import api_bp
from backend.services.schedule_service import ScheduleService


class TestRecurringTaskExclusion:
    """Test cases for recurring task deletion with exclusion pattern"""

    @pytest.fixture
    def mock_app(self):
        """Create a test Flask app with the API blueprint"""
        from flask import Flask
        app = Flask(__name__)
        app.register_blueprint(api_bp, url_prefix='/api')
        app.config['TESTING'] = True
        return app

    @pytest.fixture
    def sample_schedule_with_recurring_task(self):
        """Sample schedule with a daily recurring task"""
        return {
            "_id": ObjectId("507f1f77bcf86cd799439011"),
            "userId": "test_user_123",
            "date": "2025-01-20T00:00:00",
            "schedule": [
                {
                    "id": "recurring-task-1",
                    "text": "Daily Exercise",
                    "categories": ["Health"],
                    "completed": False,
                    "is_section": False,
                    "type": "task",
                    "is_recurring": {
                        "frequency": "daily"
                    }
                },
                {
                    "id": "regular-task-1",
                    "text": "Regular task",
                    "categories": ["Work"],
                    "completed": False,
                    "is_section": False,
                    "type": "task"
                }
            ],
            "metadata": {
                "created_at": "2025-01-20T08:00:00",
                "last_modified": "2025-01-20T08:00:00",
                "source": "manual"
            }
        }

    def test_delete_recurring_task_adds_to_exclusion_list(self, mock_app, sample_schedule_with_recurring_task):
        """Test that deleting a recurring task adds it to user's exclusion list"""

        with patch('backend.apis.routes.get_user_from_token') as mock_get_user, \
             patch('backend.apis.routes.schedule_service') as mock_schedule_service, \
             patch('backend.apis.routes.get_users_collection') as mock_get_users_collection:

            # Setup mocks
            mock_get_user.return_value = {'googleId': 'test_user_123'}
            mock_schedule_service.get_schedule_by_date.return_value = (
                True,
                {"schedule": sample_schedule_with_recurring_task["schedule"], "date": "2025-01-20"}
            )

            # Expected schedule after deletion - recurring task should be removed
            expected_schedule_after_delete = [
                {
                    "id": "regular-task-1",
                    "text": "Regular task",
                    "categories": ["Work"],
                    "completed": False,
                    "is_section": False,
                    "type": "task"
                }
            ]

            mock_schedule_service.update_schedule_tasks.return_value = (
                True,
                {
                    "schedule": expected_schedule_after_delete,
                    "date": "2025-01-20",
                    "metadata": {"totalTasks": 1}
                }
            )

            # Mock users collection
            mock_users_coll = Mock()
            mock_get_users_collection.return_value = mock_users_coll

            # Test the API endpoint
            with mock_app.test_client() as client:
                response = client.delete(
                    '/api/tasks/recurring-task-1',
                    headers={
                        'Authorization': 'Bearer valid_token',
                        'Content-Type': 'application/json'
                    },
                    json={'date': '2025-01-20'}
                )

                # Verify response
                assert response.status_code == 200
                response_data = json.loads(response.data)
                assert response_data['success'] is True

                # Verify that exclusion was added to user document
                mock_users_coll.update_one.assert_called_once()
                call_args = mock_users_coll.update_one.call_args

                # Check the update query
                user_filter = call_args[0][0]
                update_doc = call_args[0][1]

                assert user_filter == {"googleId": "test_user_123"}
                assert "$push" in update_doc
                assert "recurringTaskExclusions" in update_doc["$push"]

                exclusion_entry = update_doc["$push"]["recurringTaskExclusions"]
                assert exclusion_entry["taskText"] == "Daily Exercise"
                assert exclusion_entry["frequency"] == "daily"
                assert "excludedAt" in exclusion_entry

                # Verify that task was removed from schedule
                mock_schedule_service.update_schedule_tasks.assert_called_once()
                update_call_args = mock_schedule_service.update_schedule_tasks.call_args
                updated_schedule = update_call_args[0][2]

                # Recurring task should be removed
                recurring_tasks = [t for t in updated_schedule if t['id'] == 'recurring-task-1']
                assert len(recurring_tasks) == 0

    def test_autogenerate_filters_excluded_recurring_tasks(self):
        """Test that autogenerate_schedule filters out tasks in user's exclusion list"""

        # Create schedule service with mocked collection
        schedule_service = ScheduleService()
        mock_schedules_collection = Mock()
        mock_users_collection = Mock()
        schedule_service.schedules_collection = mock_schedules_collection

        # Mock user document with exclusion list
        user_doc = {
            "googleId": "test_user_123",
            "recurringTaskExclusions": [
                {
                    "taskText": "Daily Exercise",
                    "frequency": "daily",
                    "dayOfWeek": None,
                    "weekOfMonth": None,
                    "excludedAt": datetime.now(timezone.utc)
                }
            ]
        }

        # Previous schedule has the excluded recurring task
        previous_schedule = {
            "userId": "test_user_123",
            "date": "2025-01-19T00:00:00",
            "schedule": [
                {
                    "id": "recurring-task-1",
                    "text": "Daily Exercise",
                    "categories": ["Health"],
                    "completed": False,
                    "is_section": False,
                    "type": "task",
                    "is_recurring": {
                        "frequency": "daily"
                    }
                }
            ]
        }

        # Mock database queries
        mock_schedules_collection.find_one.side_effect = [
            None,  # No existing schedule for target date
            None,  # No recent schedule with inputs
        ]

        # Mock find() for range queries
        mock_cursor = MagicMock()
        mock_cursor.__iter__.return_value = iter([previous_schedule])
        mock_cursor.sort.return_value = mock_cursor
        mock_schedules_collection.find.return_value = mock_cursor

        # Mock users database access
        mock_schedules_collection.database = {'users': mock_users_collection}
        mock_users_collection.find_one.return_value = user_doc

        mock_schedules_collection.replace_one.return_value = Mock(upserted_id=None)

        # Test autogenerate
        with patch('backend.services.calendar_service.get_calendar_tasks_for_user_date') as mock_calendar, \
             patch('backend.services.schedule_service.get_users_collection') as mock_get_users:

            mock_calendar.return_value = []  # No calendar tasks
            mock_get_users.return_value = mock_users_collection

            success, result = schedule_service.autogenerate_schedule(
                user_id="test_user_123",
                date="2025-01-20"
            )

            # Verify success
            assert success is True
            assert result['created'] is True

            # Verify that the excluded recurring task was NOT included in the new schedule
            generated_schedule = result['schedule']
            recurring_tasks = [
                task for task in generated_schedule
                if task.get('text') == 'Daily Exercise'
            ]
            assert len(recurring_tasks) == 0, "Excluded recurring task should not appear in autogenerated schedule"

    def test_exclusion_matching_with_pattern_precision(self):
        """Test that exclusion matching uses text + pattern for precision"""

        schedule_service = ScheduleService()

        # Two tasks with same text but different patterns
        daily_task = {
            "text": "Standup",
            "is_recurring": {
                "frequency": "daily"
            }
        }

        weekly_task = {
            "text": "Standup",
            "is_recurring": {
                "frequency": "weekly",
                "dayOfWeek": "Monday"
            }
        }

        # Exclusion for daily task only
        daily_exclusion = {
            "taskText": "Standup",
            "frequency": "daily",
            "dayOfWeek": None,
            "weekOfMonth": None
        }

        # Exclusion for weekly task only
        weekly_exclusion = {
            "taskText": "Standup",
            "frequency": "weekly",
            "dayOfWeek": "Monday",
            "weekOfMonth": None
        }

        # Daily task should match daily exclusion but not weekly exclusion
        assert schedule_service._matches_exclusion(daily_task, daily_exclusion) is True
        assert schedule_service._matches_exclusion(daily_task, weekly_exclusion) is False

        # Weekly task should match weekly exclusion but not daily exclusion
        assert schedule_service._matches_exclusion(weekly_task, weekly_exclusion) is True
        assert schedule_service._matches_exclusion(weekly_task, daily_exclusion) is False

    def test_monthly_recurring_task_exclusion_matching(self):
        """Test exclusion matching for monthly recurring tasks with weekOfMonth"""

        schedule_service = ScheduleService()

        # Monthly task - first Monday of the month
        first_monday_task = {
            "text": "Monthly Review",
            "is_recurring": {
                "frequency": "monthly",
                "dayOfWeek": "Monday",
                "weekOfMonth": "first"
            }
        }

        # Monthly task - second Monday of the month
        second_monday_task = {
            "text": "Monthly Review",
            "is_recurring": {
                "frequency": "monthly",
                "dayOfWeek": "Monday",
                "weekOfMonth": "second"
            }
        }

        # Exclusion for first Monday task
        first_monday_exclusion = {
            "taskText": "Monthly Review",
            "frequency": "monthly",
            "dayOfWeek": "Monday",
            "weekOfMonth": "first"
        }

        # First Monday task should match, second Monday task should not
        assert schedule_service._matches_exclusion(first_monday_task, first_monday_exclusion) is True
        assert schedule_service._matches_exclusion(second_monday_task, first_monday_exclusion) is False

    def test_non_recurring_task_deletion_unchanged(self, mock_app, sample_schedule_with_recurring_task):
        """Test that non-recurring tasks are deleted normally (not added to exclusion list)"""

        with patch('backend.apis.routes.get_user_from_token') as mock_get_user, \
             patch('backend.apis.routes.schedule_service') as mock_schedule_service, \
             patch('backend.apis.routes.get_users_collection') as mock_get_users_collection:

            # Setup mocks
            mock_get_user.return_value = {'googleId': 'test_user_123'}
            mock_schedule_service.get_schedule_by_date.return_value = (
                True,
                {"schedule": sample_schedule_with_recurring_task["schedule"], "date": "2025-01-20"}
            )

            expected_schedule = [
                sample_schedule_with_recurring_task["schedule"][0]  # Keep recurring task
            ]

            mock_schedule_service.update_schedule_tasks.return_value = (
                True,
                {
                    "schedule": expected_schedule,
                    "date": "2025-01-20",
                    "metadata": {"totalTasks": 1}
                }
            )

            mock_users_coll = Mock()
            mock_get_users_collection.return_value = mock_users_coll

            # Test deleting non-recurring task
            with mock_app.test_client() as client:
                response = client.delete(
                    '/api/tasks/regular-task-1',  # Non-recurring task
                    headers={
                        'Authorization': 'Bearer valid_token',
                        'Content-Type': 'application/json'
                    },
                    json={'date': '2025-01-20'}
                )

                # Verify response
                assert response.status_code == 200

                # Verify that exclusion was NOT added (update_one not called for non-recurring)
                mock_users_coll.update_one.assert_not_called()

                # Task should still be removed from schedule
                mock_schedule_service.update_schedule_tasks.assert_called_once()
